```{r echo = FALSE}
# This block needs cache=FALSE to set fig.width and fig.height, and have those
# persist across cached builds.
source("utils.R", local = TRUE)
```

# PDAC Subtypes

The identification of intrinsic subtypes using gene expression data has been successfully employed in a number of different cancer settings to define broad and potentially actionable subgroups of patients. As an exemplar, the classification of colorectal cancer by gene expression profiling has identified robust and reproducible subtypes that show promise in clinical practice. mRNA profiling of PDAC by several different groups has defined at least 4 intrinsic molecular subtypes and produced 3 major classification schemes with differing nomenclature. A comparison of these schemes highlights several important similarities and dichotomies and underlines the need to align efforts to generate a new consensus classification for PDAC that better defines patient subgroups and clinical decision-making. 

Three major studies, in particular, have shaped debate concerning the classification of PDAC using gene expression profiles. The first of these, performed by [_Collisson and Sadanandam et al_](10.1038/s41575-019-0109-y), used primary resected PDAC (micro-dissected to remove stromal contamination) to define 3 subtypes referred to as Exocrine-like, Classical and Quasi-mesenchymal. Genes associated with exocrine function (digestive enzyme genes), markers of epithelial adhesion and terminal differentiation (e.g. GATA6) and gain in mesenchymal function were specifically expressed in either the Exocrine-like, Classical or Quasi-mesenchymal subtypes, respectively. In addition, the Quasi-mesenchymal subtype was correlated with high tumour grade and poor patient outcomes. 

The second major study performed by [_Moffit et al_](10.1038/ng.3398) used a supervised classification approach to informatically segregate tumour cell intrinsic gene expression signatures from “contaminating” gene expression signatures commonly associated with terminally differentiated normal pancreas (exocrine and endocrine genes signatures) and stromal cell populations (pancreatic stellate gene signatures). This analysis identified 2 major PDAC tumour cell intrinsic subtypes named Classical and Basal-like and additional tumour cell extrinsic or stromal subtypes referred to as Normal and Activated. Importantly, this study was the first to model the complex interplay between tumour cell intrinsic subtypes and specific stromal cell signals with combinations of tumour-specific and stromal subtypes associated with different patient survival. 

The third major classification scheme proposed by [_Bailey et al_](https://doi.org/10.1038/nature16965) used primary resectable PDAC with >40% cellularity to define 4 subtypes referred to as Aberrantly Differentiated Endocrine eXocrine (ADEX), Pancreatic Progenitor, Immunogenic and Squamous. These subtypes overlapped directly with the Collisson classification scheme with the exception of the Immunogenic subtype which was defined by the significant enrichment of genes associated with specific immune cell populations, including T-cells and B-cells. Although gene expression values defining the Immunogenic subtype most certainly originate from immune infiltrates resident in the tumour stroma an underlying Pancreatic Progenitor-like gene expression profile was clearly evident in tumours falling within this subtype. In addition, the Quasi-mesenchymal subtype of Collison was renamed Squamous due to the significant enrichment of several pan-squamous characteristics, including mutations in KDM6A, enrichment of the deltaNP63 isoform of p63 and a significant association with adenosquamous PDAC histology. This study also demonstrated for the first time that Squamous tumours undergo a profound epigenetic shift, with changes in DNA methylation orchestrating the down-regulation of pancreatic specific transcription factors (PDX1, GATA6, HNF1A), that control pancreatic cell fate determination, and the activation of multigene programmes regulated by deltaNTP63 and c-MYC that drive Squamous-like differentiation. Supporting a role for epigenetic dysregulation in the genesis of PDAC subtypes, the Squamous subtype was found to be enriched for mutations in COMPASS (COMplex of Proteins Associated with Set1-like) complex members KDM6A, MLL2 and MLL3 that function as chromatin modifying enzymes.


## Towards a consensus transcriptomic classification of PDAC

The transcriptomic classification of PDAC by several different groups has generated a number of interesting contrasts and ultimately divided opinion. A major point of difference concerns the inclusion of the Exocrine-like/ADEX subtype as a bona fide subtype of disease. The weight of current opinion is now favouring the exclusion of this subtype on the basis that it represents normal pancreatic contamination, however, the identification of exocrine-like/ADEX gene expression in patient-derived xenographs and cell lines suggests that further study is required. A second point of contention concerns the inclusion of a separate Immunogenic subtype. Bailey et al demonstrate that the Immunogenic subtype is a complex admixture of gene expression comprising both Pancreatic Progenitor-like and immune gene expression (predominantly associated with T-cells and B-cells). The separation of the Pancreatic Progenitor signature into immune high (Immunogenic) and immune low (Pancreatic Progenitor) suggests that signals from the underlying epithelium (Immunogenic subset) may drive tumour cell immunogenicity. Recent studies, however, argue that immune infiltrates are enriched across all tumour-intrinsic subtypes and their prevalence is primarily driven by tumour cellularity of sequenced samples. In addition, these studies advocate the use of integrated classification schemes that apply both tumour-cell intrinsic and stromal subtype signatures to optimally define prognostic PDAC subtypes.

Despite differences in nomenclature and interpretation, a direct “side by side” comparison of the established classification schemes demonstrates considerable overlap and several common themes. In particular, strong alignment exists between the Classical/Pancreatic Progenitor and Quasi-mesenchymal/Basal-like/Squamous subtypes. Together these overlapping subtypes define 2 broad prognostic classes (referred to herein as classical and basal-like) with basal-like tumours associated with significantly poorer outcomes. These classes are delineated by the differential expression of pancreatic specific transcription factors, such as GATA6, PDX1 and HNF1A, that act to specify and maintain pancreatic identity and which are lost in basal-like tumours. Importantly, the dynamic changes in gene expression observed between the classical and basal-like classes are driven by an underlying shift in the epigenome. Multiple studies have now established that the basal-like subtype is defined by changes in DNA methylation that ultimately repress pancreatic identity and activate multigene programmes that drive Basal-like differentiation. Further, despite different approaches in modelling stromal infiltrate and the ever growing number of stromal subtypes there is a clear consensus that signals from the stroma play an important role in disease progression. An outstanding question in this regard is whether tumour-cell intrinsic subtypes contribute to the levels and/or composition of stromal (fibroblasts and immune cell) infiltrate. Additional refinement and integration of tumour-cell intrinsic and stromal subtype signatures will help to drive a greater understanding of tumour-stroma crosstalk and ultimately inform better prognostic models of disease.


## PDAC subtypes and translational protocols

Findings from both COMPASS trial and pre-clinical models of PDAC demonstrate that basal-like tumors are less likely to respond to standard-of-care chemotherapy than classical tumors. Transcriptional profiling of pancreatic cancer patient-derived organoids has identified treatment stratification signatures (TSS) that can identify best responders to gemcitabine-based therapy, or to mFOLFIRINOX. When retrospectively applied to transcriptomic data from laser capture micro-dissected tumor tissues, obtained from either resected or advanced cases, these TSS were able to predict improved responses to mFOLFIRINOX or gemcitabine/nAb-Paclitaxel. Basal-like tumors were found to be significantly enriched in the mFOLFIRINOX non-sensitive group. As a corollary to these findings, it has recently been shown that GATA6 expression in tumors from patients with advanced disease RNA (using in situ hybridization) can discriminate classical and basal-like tumors. Importantly, the best progression-free survival in patients with advanced disease was found in GATA6 positive classical tumors given mFOLFIRINOX.

Detailed integrative analysis (combing both transcriptomic and genomic analyses) performed by [_Michelle Chan-Seng-Yue et al_](10.1038/s41588-019-0566-9) has demonstrated that while transcriptomic profiling can stratify PDAC into classical and basal-like subtypes the genomes of tumors falling within these same transcriptomic subtypes may exhibit considerable intra-tumour heterogeneity (ITH). Recent evidence demonstrates that both the classical and basal-like subtypes comprise at least 2 distinct subclusters that are driven by specific copy number (CN) gains in genes such as mutant KRAS and GATA6. In particular, minor and major KRAS CN imbalances can further stratify the basal-like subtype into 2 distinct subclusters, with minor KRAS CN imbalances associated with Primary disease (Stages I-III) and major KRAS CN imbalances linked to metastasis (Stage IV) and squamous-like gene expression programmes. Importantly, Stage IV tumors with Major mutant KRAS CN gains were found to be significantly more resistant to FOLFIRINOX compared to those with minor mutant KRAS CN gains. These findings are incredibly informative in that they support a model of PDAC in which ongoing genomic instability during disease progression gives rise to different molecular phenotypes.


## Transcriptomic profiling of PDAC

In this chapter, you will use your newly acquired informatic skills to analyse RNAseq data from a panel of Patient Derived Cell Lines published in [_Brunton et al. HNF4A and GATA6 Loss Reveals Therapeutically Actionable Subtypes in Pancreatic Cancer. Cell Reports 2020_](https://doi.org/10.1016/j.celrep.2020.107625)

The RNAseq data to be analysed is available here: [PDCL Subtype Data](RNASeqData/PDCL_subtyping.RData).

> ***Assignment - Please complete this chapter.***
>
> Using the data provided:
>    
> 1. Classify the PDCLs into their transcriptomic subtypes. Use the Moffitt, Collisson, Bailey and Michelle Chan-Seng-Yue classifications schemes to perform this task.
> 2. Compare these classification schemes - What similarities do you observe?
> 3. Identify biological pathways that are specifically enriched in either the Classical or Basal-like subtypes.
> 4. Identify a therapuetically actionable pathway signficantly enriched in either the Classical or Basal-like subtypes and define specific targets for therapy.
>
>


